# This is a basic workflow to help you get started with Actions

name: New Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repository_name:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create Repository
        env:
          ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORGANIZATION_NAME/repos \
            -d '{"name":"${{inputs.repository_name}}","description":"This is your ${{inputs.repository_name}} repository","homepage":"https://github.com","private":false,"has_issues":true,"has_projects":true,"has_wiki":true}'

      - uses: actions/checkout@v4
        with:
          repository: https://github.com/${{ secrets.ORGANIZATION_NAME }}/repositories/${{ inputs.repository_name }}
          path: "working_directory"

      # Runs a single command using the runners shell
      - name: Run Cookiecutter
        run: |
            cd working_directory
            pip install cookiecutter
            cookiecutter ../
